### ISSUE TITLE
Editorial issues with Effective OpenGL

### ISSUE THREAD

**Issue by NicolBolas** [g-truc/website#1]
These are editorial issues with your Effective OpenGL document. Grammar, spelling, wording, that sort of thing.
- [x] The PDF lacks a proper table of contents. That is, the kind you can bring up on the side in a PDF viewer. Also, the built-in TOC has no links to the specific locations.
- [x] There appear to be many links in the document, but none of them actually work in the PDF viewer.
- [x]  
  
  > such as Playstation libgnm
  
  I believe you meant "libgcm".
- [x]  
  
  > so why not using OpenGL like a
  
  Consider "so why not _use_ OpenGL..."
- [x]  
  
  > Alternatively, OpenGL 3.3, GL_ARB_texture_swizzle and GL_EXT_texture_swizzle provides a slightly different approach allowing to setup all components at once as shown in listing 2.2.
  
  The "allowing to setup" phrasing is a bit awkward, and "provides" should be singular. Consider rephrasing as follows:
  
  > Alternatively, OpenGL 3.3, GL_ARB_texture_swizzle and GL_EXT_texture_swizzle provide another means to setup all components at once as shown in listing 2.2.
- [x]  
  
  > In this section, we call a texture alpha, a single component texture which data is accessed in the shader with the alpha channel (.a, .w, .q). 
  
  Consider rephrasing this as follows:
  
  > In this section, let the term "texture alpha" refer to a single component texture whose data in the shader comes only from the alpha channel (.a, .w, .q).
- [x]  
  
  > sRGB  textures  have  been  introduced  to  OpenGL...
  > 
  > With  OpenGL  ES,  it  has  been  introduced  with...
  
  The "have/has been introduced" phrasing is inconsistent with prior statements, and it is somewhat awkward besides. It would be better to say that it "was introduced", as prior sections do.
- [x]  
  
  > the  none  linear  property
  
  Your probably meant "the _non-linear_ property".
- [x]  
  
  > This  is  the  case  for  BPTC,  ASTC  or ETC2  however  for  older  compression  formats,  the  situation  is  more  complex. 
  
  There should probably be a semicolon before "however".
- [x]  
  
  >  sRGB8  provides  a  better  precision  where  it  matters  the most  for  the  eyes  sensibility  and  tackle  perfectly  some  use  cases  just  particle  systems  rendering.
  
  The last phrase, starting with "tackle" doesn't seem to make sense. sRGB images tackle some use cases like particle systems?
- [x]  
  
  > alternative  to  checking  versions  and  extensions,  consists  in  creating  a  texture 
  
  Consider "consists _of_ creating".
- [x]  
  
  > to  initial  a  table
  
  Consider "to _initialize_ a table".
- [x]  
  
  >  alternative  consists  in  emulating
  
  Consider "alternative consists _of_ emulating".

**Comment by Groovounet** [comment]
Ah thanks! I'll make an update soonish. :)

**Comment by Groovounet** [comment]
Hi,

I made the changes where it made sense. libgnm, is the PS4 API, libgcm is the one for PS3.

I still have issues with the table of content. It was broken in the .docx which is fixed now but the PDF doesn't have embedded link at all at least on OSX preview. I'll investigate further.

Thanks,
Christophe

**Comment by Groovounet** [comment]
This issue is fixed. Thanks for reporting,
Christophe
