### ISSUE TITLE
Effective OpenGL, item 12: error handling in OpenGL

### ISSUE THREAD

**Issue by NicolBolas** [g-truc/website#2]
Item 12 says this about OpenGL error handling:

> However, OpenGL doesn’t guarantee the implementation behavior after an error.

From OpenGL 4.5, folio page 16:

>  Currently, when an error flag is set, results of GL operation are undefined only if an `OUT_OF_MEMORY` error has occurred. In other cases, there are no side effects unless otherwise noted; the command which generates the error is ignored so that it has no effect on GL state or framebuffer contents. Except as otherwise noted, if the generating command returns a value, it returns zero. If the generating command modifies values through a pointer argument, no change is made to these values.

The same text appears in both OpenGL ES 2.0 and desktop OpenGL 2.0. Commands that generate most errors have well-defined behavior in pretty much every version of OpenGL.

**Comment by Groovounet** [comment]
Thanks for reporting, I fixed the document!
